{% set python_min = '3.10' %}
{% set name = "pymt_nwis" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gantian127/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fcf4bfda9420607ccdd2a73edd8e094e3835d2646ba5e1af0fb3adadc93ac86a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bmi_nwis >=0.1

test:
  requires:
    - python {{ python_min }}
    - setuptools
  imports:
    - pymt_nwis

about:
  home: https://github.com/gantian127/pymt_nwis
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyMT plugin for National Water Information System Dataset
  description: |
    pymt_nwis is a package that converts bmi_nwis package into a reusable, 
    plug-and-play data component for PyMT modeling framework. This allows 
    the National Water Information System (NWIS) data to be easily coupled 
    with other data or models that expose a Basic Model Interface.
  doc_url: https://pymt-nwis.readthedocs.io/
  dev_url: https://github.com/gantian127/pymt_nwis

extra:
  recipe-maintainers:
    - gantian127
